#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Oct 14 09:54:22 CEST 2023
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
