hideOverlays = "RELOADING"
rgbProgress = false
blockOverlay = false
miniRender = false
enableScissor = false
type = "PROGRESS"
reloadText = "Edit in config!"
resetResources = false
reInitScreen = true
removeOverlayAtEnd = true
earlyPackStatusSend = false
doubleLoad = "NONE"
animationSpeed = 1000.0
